name: olearis_test_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  auto_route: ^9.3.0+1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

flutter_gen:
  output: lib/config/assets/gen/
